// Sample data for the luxury e-commerce platform
// Re-export getLocalizedField for convenience
export { getLocalizedField } from './i18n';

export const sampleCategories = [
  {
    id: 'cat-1',
    slug: 'clothing',
    nameEn: 'Clothing',
    nameDe: 'Kleidung',
    nameSr: 'Odeća',
    descriptionEn: 'Luxury designer clothing',
    descriptionDe: 'Luxus Designer-Kleidung',
    descriptionSr: 'Luksuzna dizajnerska odeća',
    image: 'https://images.unsplash.com/photo-1558171813-4c088753af8f?w=800',
    displayOrder: 1,
  },
  {
    id: 'cat-2',
    slug: 'shoes',
    nameEn: 'Shoes',
    nameDe: 'Schuhe',
    nameSr: 'Obuća',
    descriptionEn: 'Premium designer footwear',
    descriptionDe: 'Premium Designer-Schuhe',
    descriptionSr: 'Premium dizajnerska obuća',
    image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800',
    displayOrder: 2,
  },
  {
    id: 'cat-3',
    slug: 'bags',
    nameEn: 'Bags',
    nameDe: 'Taschen',
    nameSr: 'Torbe',
    descriptionEn: 'Luxury designer bags',
    descriptionDe: 'Luxus Designer-Taschen',
    descriptionSr: 'Luksuzne dizajnerske torbe',
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800',
    displayOrder: 3,
  },
  {
    id: 'cat-4',
    slug: 'jewelry',
    nameEn: 'Jewelry',
    nameDe: 'Schmuck',
    nameSr: 'Nakit',
    descriptionEn: 'Exquisite fine jewelry',
    descriptionDe: 'Exquisiter Schmuck',
    descriptionSr: 'Izuzetan fini nakit',
    image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800',
    displayOrder: 4,
  },
];

export const sampleProducts = [
  {
    id: 'prod-1',
    sku: 'GUC-DRS-001',
    slug: 'silk-evening-gown',
    nameEn: 'Silk Evening Gown',
    nameDe: 'Seiden-Abendkleid',
    nameSr: 'Svilena Večernja Haljina',
    descriptionEn: 'An exquisite silk evening gown featuring delicate hand-embroidered details and a flowing silhouette. Crafted in Italy from the finest mulberry silk.',
    descriptionDe: 'Ein exquisites Seiden-Abendkleid mit zarten, handgestickten Details und einer fließenden Silhouette.',
    descriptionSr: 'Izuzetna svilena večernja haljina sa delikatnim ručno vezenim detaljima i lepršavom siluetom.',
    brand: 'Gucci',
    price: 4850,
    comparePrice: null,
    categoryId: 'cat-1',
    isFeatured: true,
    isNew: true,
    images: [
      { id: 'img-1a', url: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800', isPrimary: true },
      { id: 'img-1b', url: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=800', isPrimary: false },
    ],
    variants: [
      { id: 'var-1a', size: 'XS', color: 'Noir', stock: 3 },
      { id: 'var-1b', size: 'S', color: 'Noir', stock: 5 },
      { id: 'var-1c', size: 'M', color: 'Noir', stock: 4 },
      { id: 'var-1d', size: 'L', color: 'Noir', stock: 2 },
    ],
  },
  {
    id: 'prod-2',
    sku: 'HER-BAG-001',
    slug: 'birkin-25',
    nameEn: 'Birkin 25',
    nameDe: 'Birkin 25',
    nameSr: 'Birkin 25',
    descriptionEn: 'The iconic Birkin bag in Togo leather with palladium hardware. A timeless investment piece that defines luxury.',
    descriptionDe: 'Die ikonische Birkin-Tasche aus Togo-Leder mit Palladium-Beschlägen.',
    descriptionSr: 'Ikonična Birkin torba od Togo kože sa paladijumskim detaljima.',
    brand: 'Hermès',
    price: 12500,
    comparePrice: null,
    categoryId: 'cat-3',
    isFeatured: true,
    isNew: false,
    images: [
      { id: 'img-2a', url: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800', isPrimary: true },
    ],
    variants: [
      { id: 'var-2a', size: '25', color: 'Noir', stock: 1 },
      { id: 'var-2b', size: '25', color: 'Gold', stock: 1 },
    ],
  },
  {
    id: 'prod-3',
    sku: 'LV-SHO-001',
    slug: 'archlight-sneaker',
    nameEn: 'Archlight Sneaker',
    nameDe: 'Archlight Sneaker',
    nameSr: 'Archlight Patike',
    descriptionEn: 'Futuristic sneakers featuring the signature wave-shaped outsole. A perfect blend of comfort and avant-garde design.',
    descriptionDe: 'Futuristische Sneaker mit der charakteristischen wellenförmigen Außensohle.',
    descriptionSr: 'Futurističke patike sa prepoznatljivim đonom u obliku talasa.',
    brand: 'Louis Vuitton',
    price: 1290,
    comparePrice: null,
    categoryId: 'cat-2',
    isFeatured: true,
    isNew: true,
    images: [
      { id: 'img-3a', url: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800', isPrimary: true },
    ],
    variants: [
      { id: 'var-3a', size: '36', color: 'White', stock: 4 },
      { id: 'var-3b', size: '37', color: 'White', stock: 6 },
      { id: 'var-3c', size: '38', color: 'White', stock: 8 },
      { id: 'var-3d', size: '39', color: 'White', stock: 5 },
      { id: 'var-3e', size: '40', color: 'White', stock: 3 },
    ],
  },
  {
    id: 'prod-4',
    sku: 'CAR-JWL-001',
    slug: 'love-bracelet',
    nameEn: 'Love Bracelet',
    nameDe: 'Love Armband',
    nameSr: 'Love Narukvica',
    descriptionEn: 'The iconic Love bracelet in 18K yellow gold. Features the signature screw motif and comes with a screwdriver.',
    descriptionDe: 'Das ikonische Love-Armband aus 18K Gelbgold mit dem charakteristischen Schraubenmotiv.',
    descriptionSr: '18K zlatna Love narukvica sa ikoničnim motivom zavrtnja.',
    brand: 'Cartier',
    price: 7050,
    comparePrice: null,
    categoryId: 'cat-4',
    isFeatured: true,
    isNew: false,
    images: [
      { id: 'img-4a', url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800', isPrimary: true },
    ],
    variants: [
      { id: 'var-4a', size: '16', color: 'Yellow Gold', stock: 2 },
      { id: 'var-4b', size: '17', color: 'Yellow Gold', stock: 3 },
      { id: 'var-4c', size: '18', color: 'Yellow Gold', stock: 2 },
    ],
  },
  {
    id: 'prod-5',
    sku: 'DIO-DRS-001',
    slug: 'bar-jacket',
    nameEn: 'Bar Jacket',
    nameDe: 'Bar Jacke',
    nameSr: 'Bar Jakna',
    descriptionEn: 'The legendary Bar jacket reimagined. Crafted from virgin wool with the signature nipped waist and rounded hips.',
    descriptionDe: 'Die legendäre Bar-Jacke neu interpretiert. Aus Schurwolle gefertigt.',
    descriptionSr: 'Legendarna Bar jakna u modernoj interpretaciji. Izrađena od devičanske vune.',
    brand: 'Dior',
    price: 3800,
    comparePrice: null,
    categoryId: 'cat-1',
    isFeatured: true,
    isNew: false,
    images: [
      { id: 'img-5a', url: 'https://images.unsplash.com/photo-1539533113208-f6df8cc8b543?w=800', isPrimary: true },
    ],
    variants: [
      { id: 'var-5a', size: 'FR34', color: 'Ecru', stock: 2 },
      { id: 'var-5b', size: 'FR36', color: 'Ecru', stock: 3 },
      { id: 'var-5c', size: 'FR38', color: 'Ecru', stock: 4 },
      { id: 'var-5d', size: 'FR40', color: 'Ecru', stock: 2 },
    ],
  },
  {
    id: 'prod-6',
    sku: 'PRA-BAG-001',
    slug: 'saffiano-galleria',
    nameEn: 'Saffiano Galleria',
    nameDe: 'Saffiano Galleria',
    nameSr: 'Saffiano Galleria',
    descriptionEn: 'The iconic Galleria bag in Saffiano leather. Features gold-tone hardware and multiple compartments.',
    descriptionDe: 'Die ikonische Galleria-Tasche aus Saffiano-Leder mit goldfarbenen Beschlägen.',
    descriptionSr: 'Ikonična Galleria torba od Saffiano kože sa zlatnim detaljima.',
    brand: 'Prada',
    price: 2950,
    comparePrice: 3200,
    categoryId: 'cat-3',
    isFeatured: false,
    isNew: false,
    images: [
      { id: 'img-6a', url: 'https://images.unsplash.com/photo-1591561954557-26941169b49e?w=800', isPrimary: true },
    ],
    variants: [
      { id: 'var-6a', size: 'Medium', color: 'Nero', stock: 5 },
      { id: 'var-6b', size: 'Medium', color: 'Cameo', stock: 3 },
    ],
  },
  {
    id: 'prod-7',
    sku: 'CHL-SHO-001',
    slug: 'rylee-ankle-boot',
    nameEn: 'Rylee Ankle Boot',
    nameDe: 'Rylee Stiefelette',
    nameSr: 'Rylee Čizmica',
    descriptionEn: 'Western-inspired ankle boot in smooth calfskin with a stacked heel and pointed toe.',
    descriptionDe: 'Western-inspirierte Stiefelette aus glattem Kalbsleder.',
    descriptionSr: 'Čizmica inspirisana divljim zapadom od glatke teleće kože.',
    brand: 'Chloé',
    price: 1150,
    comparePrice: null,
    categoryId: 'cat-2',
    isFeatured: false,
    isNew: true,
    images: [
      { id: 'img-7a', url: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800', isPrimary: true },
    ],
    variants: [
      { id: 'var-7a', size: '36', color: 'Tan', stock: 3 },
      { id: 'var-7b', size: '37', color: 'Tan', stock: 5 },
      { id: 'var-7c', size: '38', color: 'Tan', stock: 4 },
      { id: 'var-7d', size: '39', color: 'Tan', stock: 2 },
    ],
  },
  {
    id: 'prod-8',
    sku: 'BVL-JWL-001',
    slug: 'serpenti-viper-necklace',
    nameEn: 'Serpenti Viper Necklace',
    nameDe: 'Serpenti Viper Halskette',
    nameSr: 'Serpenti Viper Ogrlica',
    descriptionEn: 'The Serpenti Viper necklace in 18K white gold with pavé diamonds. A statement piece of exceptional craftsmanship.',
    descriptionDe: 'Die Serpenti Viper Halskette aus 18K Weißgold mit Pavé-Diamanten.',
    descriptionSr: 'Serpenti Viper ogrlica od 18K belog zlata sa pavé dijamantima.',
    brand: 'Bulgari',
    price: 21500,
    comparePrice: null,
    categoryId: 'cat-4',
    isFeatured: true,
    isNew: false,
    images: [
      { id: 'img-8a', url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800', isPrimary: true },
    ],
    variants: [
      { id: 'var-8a', size: 'One Size', color: 'White Gold', stock: 1 },
    ],
  },
];

export type SampleProduct = typeof sampleProducts[number];
export type SampleCategory = typeof sampleCategories[number];
